/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

export * from './model';

