/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

/**
* Contains information about a single blog post.
*/
export interface BlogPost {
  /**
  * The unique blog post ID.
  */
  Id?: string;
  /**
  * The date/time that the article was published.
  */
  PublicationDate?: string;
  /**
  * The blog category.
  */
  Tag?: string;
  /**
  * The article's main title.
  */
  Title?: string;
  /**
  * An article summary.
  */
  Summary?: string;
  /**
  * A UserProfile object that describes the blog author.
  */
  AuthorProfile?: UserProfile;
}

/**
* The user profile of a blog author.
*/
export interface UserProfile {
  /**
  * The user's  first and last name.
  */
  FullName?: string;
  /**
  * The URL of the user's profile image.
  */
  ImageUrl?: string;
  /**
  * The user's role or job title.
  */
  Role?: string;
}
