/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { BlogPost } from '../model';
import { BlogAPIService } from '../services/blog-a-p-i.service';
import { PostInfoComponent } from './Blog/post-info.component';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  imports: [PostInfoComponent, NgIcon, CommonModule]
})
export class HomeComponent implements OnInit {
  public posts$!: Observable<BlogPost[] | undefined>;

  constructor(
    private blogAPIService: BlogAPIService
  ) {}

  public ngOnInit(): void {
    this.posts$ = this.blogAPIService.listPosts();
  }
}
