/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    importProvidersFrom(BrowserModule),
    provideRouter(routes)
  ]
};
