/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { Routes } from '@angular/router';
import { BlogPostComponent } from './components/Blog/blog-post.component';
import { HomeComponent } from './components/home.component';

export const routes: Routes = [
  {
    path: 'home',
    component: HomeComponent
  },
  {
    path: 'blog-post/:postId',
    component: BlogPostComponent
  },
  {
    path: '',
    redirectTo: '/home',
    pathMatch: 'full'
  }
];
