/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { Injectable } from '@angular/core';
import { BlogPost } from '../model';
import { mockPostData } from './blog-a-p-i.service.mock-data';
import { Observable, of } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class BlogAPIService {

  public listPosts(): Observable<BlogPost[]> {
    return of(
      mockPostData
    );
  }

  public getPost(postId: string | null): Observable<BlogPost | undefined> {
    return of(
      mockPostData
      .find((item) => { return (postId == null || item.Id === postId); })
    );
  }
}
