/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { BlogPost } from '../model';

export const mockPostData: BlogPost[] = [
  {
    Id: '9bJ3tAkUGJ',
    PublicationDate: 'Mar 16, 2020',
    Tag: 'Marketing',
    Title: 'Boost your conversion rate',
    Summary: 'Illo sint voluptas. Error voluptates culpa eligendi. Hic vel totam vitae illo. Non aliquid explicabo necessitatibus unde. Sed exercitationem placeat consectetur nulla deserunt vel. Iusto corrupti dicta.',
    AuthorProfile: {
      FullName: 'Micheal Foster',
      ImageUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      Role: 'Co-Founder / CTO'
    }
  },
  {
    Id: 'kamSnHv1tB',
    PublicationDate: 'Mar 10, 2020',
    Tag: 'Sales',
    Title: 'How to use search engine optimization to drive sales',
    Summary: 'Optio cum necessitatibus dolor voluptatum provident commodi et. Qui aperiam fugiat nemo cumque.',
    AuthorProfile: {
      FullName: 'Lindsay Walton',
      ImageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      Role: 'Front-end Developer'
    }
  },
  {
    Id: 'agXgcaGVod',
    PublicationDate: 'Feb 12, 2020',
    Tag: 'Business',
    Title: 'Improve your customer experience',
    Summary: 'Cupiditate maiores ullam eveniet adipisci in doloribus nulla minus. Voluptas iusto libero adipisci rem et corporis. Nostrud sint anim sunt aliqua. Nulla eu labore irure incididunt velit cillum quis magna dolore.',
    AuthorProfile: {
      FullName: 'Tom Cook',
      ImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      Role: 'Director of Product'
    }
  }
];
