/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';

bootstrapApplication(AppComponent, appConfig)
  .catch(err => console.error(err));
