/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps using leading UI
* libraries.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Componentize your Tailwind app - final, at
* https://www.jitblox.com/project/LXuOtSfcRL/componentize-your-tailwind-app-final
*/

import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { BlogPost } from '../../model';

@Component({
  selector: 'app-post-info',
  standalone: true,
  templateUrl: './post-info.component.html',
  imports: [RouterLink, NgIcon, CommonModule]
})
export class PostInfoComponent {
  @Input() public post?: BlogPost | null;

  constructor() {}
}
